# Generated by Django 5.2.6 on 2025-09-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(null=True, upload_to="project_images/"),
        ),
    ]
